# fly.toml app configuration file generated for long-darkness-6257 on 2023-10-21T11:14:28+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "long-darkness-6257"
primary_region = "nrt"
swap_size_mb = 512
console_command = "/rails/bin/rails console"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
swap_size_mb = 512