# fly.toml app configuration file generated for app06 on 2023-09-28T21:09:33+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "app06"
primary_region = "nrt"
swap_size_mb = 512
console_command = "/rails/bin/rails console"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
